version: "2"
services:

  worker:
    build: './'
    links:
      - rabbitmq
    ports:
      - '8888:8888'

    environment:
      - JUPYTER_TOKEN=hi

    volumes:
      - ../jupyter/:/usr/src/app/jupyter

  # redis:
  #   image: 'redis:alpine3.17'
  #   ports:
  #     - '6379:6379'

  rabbitmq:
    image: 'rabbitmq:3.10.20-alpine'
    environment:
      - RABBITMQ_USER=myuser
      - RABBITMQ_PASSWORD=mypassword
      - RABBITMQ_VHOST=myvhost
      - RABBITMQ_PID_FILE = /var/lib/rabbitmq/mnesia/rabbitmq

    ports:
      -'5672:5672'
    command: 
      sh -c "add init.sh /init.sh &&
      run chmod +x /init.sh &&
      /init.sh"

      


